### 쿠폰 생성 (POST /api/coupons/create)
POST http://localhost:8083/api/coupons/create?couponPolicyId=1&couponName=Coupon1&couponTarget=Target1&couponTargetId=123&couponDeadline=2024-12-31T23:59:59Z
Content-Type: application/json

### 쿠폰 조회 (GET /api/coupons/{couponId})
GET http://localhost:8083/api/coupons/1
Accept: application/json

### 모든 쿠폰 조회 (GET /api/coupons/all)
GET http://localhost:8083/api/coupons/all
Accept: application/json

### 쿠폰 ID 리스트로 쿠폰 조회 (GET /api/coupons/list)
GET http://localhost:8083/api/coupons/list?couponIds=1,2,3
Accept: application/json

### 쿠폰 사용 (POST /api/coupons/use/{couponId})
POST http://localhost:8083/api/coupons/use/1
Accept: application/json

### 쿠폰 비활성화 (POST /api/coupons/deactivate/{couponId})
POST http://localhost:8083/api/coupons/deactivate/1
Accept: application/json
