### 쿠폰 정책 생성
POST http://localhost:8083/api/policies
Content-Type: application/json

{
  "couponPolicyName": "Winter Discount",
  "minPurchaseAmount": 10000,
  "discountType": "PERCENTAGE",
  "discountValue": 10,
  "maxDiscountAmount": 5000
}

### 쿠폰 정책 수정
PUT http://localhost:8083/api/policies/1
Content-Type: application/json

{
  "couponPolicyName": "Updated Winter Discount",
  "minPurchaseAmount": 15000,
  "discountType": "PERCENTAGE",
  "discountValue": 15,
  "maxDiscountAmount": 6000,
  "eventType": "welcome"
}

### 모든 쿠폰 정책 조회 삭제 안된
GET http://localhost:8083/api/policies

### 모든 쿠폰 정책 조회 삭제 된
GET http://localhost:8083/api/policies?deleted=true

### 특정 쿠폰 정책 조회
GET http://localhost:8083/api/policies/1

### 쿠폰 정책 삭제
DELETE http://localhost:8083/api/policies/1

### welcome 정책 조회
GET http://localhost:8083/api/policies/welcome/eventType